name: Deploy to Azure

on:
  push:
    branches: [ main ]
  workflow_dispatch: # Allow manual trigger

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
    
    - name: Restore dependencies
      run: dotnet restore zuHause/zuHause.csproj
    
    - name: Build
      run: dotnet build zuHause/zuHause.csproj --configuration Release
    
    - name: Run Entity Framework Migrations
      env:
        ConnectionStrings__ZuhauseDb: ${{ secrets.AZURE_SQL_CONNECTION_STRING }}
      run: |
        cd zuHause
        dotnet ef database update --configuration Release
    
    - name: Publish
      run: dotnet publish zuHause/zuHause.csproj --configuration Release --output ./myapp
    
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ./myapp